### ISSUE TITLE
Create a program in python which scrapes news from websites

### ISSUE THREAD

**Issue by pravee42** [pravee42/Hacktoberfest2022-python#1]

**Comment by pravee42** [comment]
yes you can

**Comment by pravee42** [comment]
make sure you completed before 12PM today

**Comment by pravee42** [comment]
i am also an full stack developer if you any doubts in while scraping you can contact me

**Comment by pravee42** [comment]
@astitvaveergarg dont u want to contribute to this issue

**Comment by astitvaveergarg** [comment]
Actually I want To, But I got Some Personal Issue, So I will Not Be Able To Do It Right Now, I apologise For Inconvenience

**Comment by pravee42** [comment]
ok no problem
