### ISSUE TITLE
I have the code for my first pr (i have the code to upload)

### ISSUE THREAD

**Issue by Flash007-alt** [pravee42/Hacktoberfest2022-python#11]

**Comment by pravee42** [comment]
ok do it
i will assign you but before 9pm, tonight

- [ ]  tick this before making PR

**Comment by Flash007-alt** [comment]
> ok do it i will assign you but before 9pm, tonight
> 
> * [ ✓]   tick this before making PR

**Comment by Flash007-alt** [comment]
def Fibonacci(n):
    if n<0:
        print("Incorrect Input")
    elif n==0:
        return 0
    elif n==1 or n==2:
        return 1
    else:
        return Fibonacci(n-1) + Fibonacci(n-2)

x=int(input("Enter a Number :"))

print(Fibonacci(x))

**Comment by pravee42** [comment]
@Flash007-alt you need not want to close this issue i will close it

**Comment by Flash007-alt** [comment]
Sorry I am just a beginner, sorry for the trouble caused by me 
:)

**Comment by pravee42** [comment]
ok i closed this
