### ISSUE TITLE
I have the code for my second pr (i have the code to upload)

### ISSUE THREAD

**Issue by Flash007-alt** [pravee42/Hacktoberfest2022-python#12]

**Comment by pravee42** [comment]
- [ ]  you can but before 9pm, tonight
- [ ] explain the code in the comment at the top

**Comment by Flash007-alt** [comment]
> * [✓]   you can but before 9pm, tonight
> * [✓ ]  explain the code in the comment at the top

sorry for replying late. I was logged out so i couldn't see u r msg. 
Also is is possible for u to remove the spam remark as i accidently deleted it . pls

![image](https://user-images.githubusercontent.com/73688066/138930349-e383f11e-1cbb-403f-a21a-5c3151f82223.png)

**Comment by Flash007-alt** [comment]
# Python program to check if the number is an Armstrong number or not


num = int(input("Enter a number: "))
sum = 0

temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

**Comment by Flash007-alt** [comment]
for the third pr it shows like this 
![image](https://user-images.githubusercontent.com/73688066/138983577-44cc58ac-f8b7-44f1-9226-79085eb1b716.png)
Is there any work around it ?
