### ISSUE TITLE
I have the code for my fourth pr (i have the code to upload)

### ISSUE THREAD

**Issue by Flash007-alt** [pravee42/Hacktoberfest2022-python#14]

**Comment by pravee42** [comment]
- [ ] you can but before 10pm tonight

**Comment by Flash007-alt** [comment]
def calculate_hcf(x, y):   
    if x > y:  
        smaller = y  
    else:  
        smaller = x  
    for i in range(1,smaller + 1):  
        if((x % i == 0) and (y % i == 0)):  
            hcf = i  
    return hcf  
  
num1 = int(input("Enter first number: "))  
num2 = int(input("Enter second number: "))  
 
print("The H.C.F. of", num1,"and", num2,"is", calculate_hcf(num1, num2))
