### ISSUE TITLE
Create a program in python which sorts an array

### ISSUE THREAD

**Issue by pravee42** [pravee42/Hacktoberfest2022-python#2]

**Comment by raviprasanthgit** [comment]
Hi @pravee42 ,
I ll solve this and raise a PR

**Comment by pravee42** [comment]
@raviprasanthgit go ahead and solve this

**Comment by raviprasanthgit** [comment]
@pravee42 Are you expecting a simple python program to sort the array in ascending and descending order for integer , decimal and string . Correct me if my understanding is wrong

**Comment by pravee42** [comment]
Yes

- [ ] Complete this before 6:00pm
- [ ] submit the code
- [ ] create an readme file explain the code there 
- [ ] send the pull request
- [ ] comment here that you have made pull request

**Comment by pravee42** [comment]
for integer
