### ISSUE TITLE
Hacktoberfest Contributions are not Working

### ISSUE THREAD

**Issue by JoeFurfaro** [pravee42/Hacktoberfest2022-python#21]
![8d264e6fa5f16c4d3d41eec490c77920](https://user-images.githubusercontent.com/11153746/138918203-76491de1-7c84-4f8e-a05f-65953fd5d17a.png)

@pravee42 I think you must add specifically the `hacktoberfest` topic to the repository to participate

**Comment by pravee42** [comment]
Now thay might work I added the label

**Comment by pravee42** [comment]
is it now worked
